export const APP_NAME = 'Solar Business Platform';

export const QUERY_KEYS = {
  products: 'products',
  services: 'services',
  articles: 'articles',
  videos: 'videos',
  testimonials: 'testimonials',
  faqs: 'faqs',
  leads: 'leads',
  settings: 'settings',
  dashboard: 'dashboard',
  analytics: 'analytics',
  notifications: 'notifications',
} as const;

export const ROUTES = {
  home: '/',
  products: '/products',
  productDetail: (slug: string) => `/products/${slug}`,
  services: '/services',
  serviceDetail: (slug: string) => `/services/${slug}`,
  articles: '/articles',
  articleDetail: (slug: string) => `/articles/${slug}`,
  videos: '/videos',
  search: '/search',
  faq: '/faq',
  contact: '/contact',
  support: '/support',
  technicalSupport: '/support/technical',
  videoCall: '/support/video-call',
  siteVisit: '/support/site-visit',
  installation: '/support/installation',
  about: '/about',
  // Admin
  adminLogin: '/admin/login',
  adminDashboard: '/admin',
  adminProducts: '/admin/products',
  adminCategories: '/admin/categories',
  adminServices: '/admin/services',
  adminArticles: '/admin/articles',
  adminVideos: '/admin/videos',
  adminLeads: '/admin/leads',
  adminTestimonials: '/admin/testimonials',
  adminFaqs: '/admin/faqs',
  adminNotifications: '/admin/notifications',
  adminMedia: '/admin/media',
  adminSettings: '/admin/settings',
  adminChangePassword: '/admin/change-password',
} as const;
